import React, { useEffect, useState } from 'react';
import { fetchInsightsHistory } from '../services/api';
import PageHeader from '../components/PageHeader';

const ArtificialIntelligence = () => {
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(true);
    const [filterType, setFilterType] = useState('');

    useEffect(() => {
        loadHistory();
    }, [filterType]);

    const loadHistory = async () => {
        setLoading(true);
        try {
            const filters = {};
            if (filterType) filters.type = filterType;

            const data = await fetchInsightsHistory(filters);
            setHistory(data || []);
        } catch (err) {
            console.error("Failed to load insights", err);
        } finally {
            setLoading(false);
        }
    };

    const containerStyle = {
        padding: '20px',
        maxWidth: '1200px',
        margin: '0 auto'
    };

    const headerStyle = {
        textAlign: 'center',
        marginBottom: '30px',
        color: '#F8FAFC'
    };

    const typeBadgeStyle = (type) => {
        let bg = '#95a5a6';
        if (type === 'DEMAND_SPIKE') bg = '#e74c3c'; // Red
        if (type === 'DEMAND_DROP') bg = '#f39c12'; // Orange
        if (type === 'UPCOMING_PATTERN') bg = '#8e44ad'; // Purple
        if (type === 'INACTIVE_STOCK') bg = '#7f8c8d'; // Grey
        if (type === 'STOCK_RISK') bg = '#c0392b'; // Dark Red

        return {
            backgroundColor: bg,
            color: 'white',
            padding: '4px 8px',
            borderRadius: '4px',
            fontSize: '0.85rem',
            fontWeight: 'bold'
        };
    };

    return (
        <div>
            <PageHeader title="AI Assistant History" icon="🧠" />

            <p className="text-muted mb-24" style={{ textAlign: 'center' }}>
                A complete log of all smart insights generated by the system.
            </p>

            <div style={{ marginBottom: '20px', textAlign: 'right' }}>
                <select
                    className="dark-input"
                    style={{ width: 'auto' }}
                    value={filterType}
                    onChange={(e) => setFilterType(e.target.value)}
                >
                    <option value="">All Types</option>
                    <option value="DEMAND_SPIKE">Demand Spike</option>
                    <option value="DEMAND_DROP">Demand Drop</option>
                    <option value="UPCOMING_PATTERN">Upcoming Pattern</option>
                    <option value="STOCK_RISK">Stock Risk</option>
                    <option value="INACTIVE_STOCK">Inactive Stock</option>
                </select>
            </div>

            {loading ? (
                <div style={{ textAlign: 'center', padding: '20px', color: '#94A3B8' }}>⏳ Loading insights...</div>
            ) : history.length === 0 ? (
                <div className="dark-card" style={{ textAlign: 'center', padding: '40px 20px', color: '#94A3B8', border: '2px dashed #334155' }}>
                    <h3 style={{ marginBottom: '10px', color: '#F8FAFC' }}>No insights generated yet.</h3>
                    <p style={{ margin: 0 }}>The AI will analyze your sales data over time and provide actions here.</p>
                </div>
            ) : (
                <div className="table-container">
                    <table className="dark-table">
                        <thead>
                            <tr>
                                <th>Date Generated</th>
                                <th>Type</th>
                                <th>Product</th>
                                <th>Insight Message</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {history.length > 0 && (
                                history.map((item) => (
                                    <tr key={item._id}>
                                        <td>{item?.generatedAt ? new Date(item.generatedAt).toLocaleString() : 'N/A'}</td>
                                        <td>
                                            <span style={typeBadgeStyle(item?.insightType)}>
                                                {item?.insightType ? item.insightType.replace('_', ' ') : 'UNKNOWN'}
                                            </span>
                                        </td>
                                        <td><strong>{item?.productName || 'Unknown Product'}</strong></td>
                                        <td>{item?.message || ''}</td>
                                        <td>
                                            <span style={{
                                                color: item?.status === 'active' ? '#10B981' : '#64748B',
                                                fontWeight: 'bold'
                                            }}>
                                                {item?.status ? item.status.toUpperCase() : 'N/A'}
                                            </span>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            )}
            </div>
    );
};

export default ArtificialIntelligence;
